name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'apps/api/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}'
          heroku_app_name: 'tarki-api'
          appdir: 'apps/api'
          procfile: 'web: node dist/main'
